spring.application.name=LearnSpringBoot
server.port=8081

app.info.name=Rizz E-Commerce Enterprise
app.info.version=1.0.0
app.info.is-awesome=true

# * Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/learn_springboot
spring.datasource.username=postgres
spring.datasource.password=177013

# * JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
