# --- Konfigurasi Standar Aplikasi (Aman di-hardcode) ---
spring.application.name=LearnSpringBoot
app.info.name=Rizz E-Commerce Enterprise
app.info.version=1.0.0
app.info.is-awesome=true

# --- Pengaturan Server (Ambil dari .env, kasih default 8080) ---
server.port=${SERVER_PORT:8080}

# --- Database Config (Ambil dari .env tanpa default) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- JPA / Hibernate Configuration (Aman di-hardcode) ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.cache=TRACE

# Redis Connection (Upstash - pakai URL langsung)
spring.data.redis.url=${REDIS_URL}

# Cache Config
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=learnapp:

