# --- Konfigurasi Standar Aplikasi (Aman di-hardcode) ---
spring.application.name=LearnSpringBoot
app.info.name=Rizz E-Commerce Enterprise
app.info.version=1.0.0
app.info.is-awesome=true

# --- Pengaturan Server (Ambil dari .env, kasih default 8080) ---
server.port=${SERVER_PORT:8080}

# --- Database Config (Ambil dari .env tanpa default) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- JPA / Hibernate Configuration (Aman di-hardcode) ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.cache=TRACE

# Redis Connection (Upstash - pakai URL langsung)
spring.data.redis.url=${REDIS_URL}

# Cache Config
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=learnapp:

# ——— Actuator Configuration ———

# Expose semua endpoint (kita akan secure nanti)
management.endpoints.web.exposure.include=health,info,metrics,caches,loggers,env,scheduledtasks

# Tampilkan detail health (termasuk DB & Redis status)
management.endpoint.health.show-details=when-authorized

# Base path (default /actuator, biarkan default)
management.endpoints.web.base-path=/actuator

# Info endpoint — isi metadata app
info.app.name=Learn Spring Boot
info.app.version=1.0.0
info.app.description=Spring Boot 4 REST API Learning Project
info.java.version=${java.version}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.observations.annotations.enabled=true

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
spring.threads.virtual.enabled=true
spring.main.keep-alive=true
